apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
  namespace: minio
spec:
  capacity:
    storage: 10Gi  # Ajuste o tamanho conforme necessário
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-k8s/cloud-native-storage/minio # Caminho no servidor NFS
    server: 192.168.15.146      # IP do servidor NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Deve corresponder ao tamanho do PV
  volumeName: pv-minio
