apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama-base
  namespace: ollama
spec:
  capacity:
    storage: 5Gi  # Ajuste o tamanho conforme necessário
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-k8s/ollama/base  # Caminho no servidor NFS
    server: 192.168.15.146      # IP do servidor NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-base
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Deve corresponder ao tamanho do PV
  volumeName: pv-ollama-base
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama-models-llama3
  namespace: ollama
spec:
  capacity:
    storage: 15Gi  # Ajuste o tamanho conforme necessário
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-k8s/ollama/models/llama3  # Caminho no servidor NFS
    server: 192.168.15.146      # IP do servidor NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-models-llama3
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi  # Deve corresponder ao tamanho do PV
  volumeName: pv-ollama-models-llama3

