---
apiVersion: v1
kind: Service
metadata:
  name: svc-ollama-ai
  namespace: ollama
spec:
  type: ClusterIP
  ports:
  - name: ollama-tcp
    port: 11434
    targetPort: http-ollama
    protocol: TCP
  selector:
    app: ollama