---
apiVersion: v1
kind: Service
metadata:
  name: svce-ollama-ai
  namespace: ollama
spec:
  type: NodePort
  ports:
  - name: ollama-tcp
    nodePort: 30005
    port: 80
    targetPort: http-ollama
    protocol: TCP
  selector:
    app: ollama