apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq
  namespace: rabbitmq
spec:
  capacity:
    storage: 5Gi  # Ajuste o tamanho conforme necessário
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage-k8s/streaming-messaging/rabbitmq  # Caminho no servidor NFS
    server: 192.168.15.146      # IP do servidor NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Deve corresponder ao tamanho do PV
  volumeName: pv-rabbitmq
