apiVersion: v1
kind: Secret
metadata:
  name: s-rabbitmq
  namespace: rabbitmq
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0bXE= # rabbitmq
  RABBITMQ_DEFAULT_PASS: U3ZjUmFiYml0TXE= # SvcRabbitMq