---
apiVersion: v1
kind: Service
metadata:
  name: svce-minio-console
  namespace: minio
  labels:
    app: minio
    component: bucket
spec:
  type: NodePort
  ports:
  - name: minio-tcp
    nodePort: 30001
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: svce-minio-api
  namespace: minio
  labels:
    app: minio
    component: bucket
spec:
  type: NodePort
  ports:
  - name: minio-tcp
    nodePort: 30002
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: svc-minio-api
  namespace: minio
  labels:
    app: minio
    component: bucket
spec:
  type: ClusterIP
  ports:
  - name: minio-tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio    