apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "kubernetes.io/hostname"
      #               operator: In
      #               values:
      #                 - "k8s-02"
      #         - matchExpressions:
      #             - key: apps
      #               operator: In
      #               values:
      #                 - services
      containers:
        - name: minio
          securityContext:
            seLinuxOptions:
              type: "spc_t"
              level: s0:c525,c600
          image: minio/minio:RELEASE.2024-11-07T00-52-20Z
          args:
            - minio
            - server
            - /data
            - --console-address
            - :9090
          env:
            - name: TZ
              value: America/Sao_Paulo

            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_ROOT_PASSWORD

            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_SECRET_KEY
            # get metrics the minio
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
            - name: MINIO_PROMETHEUS_URL
              value: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
          ports:
            - name: "9000-minioapi"
              containerPort: 9000
            - name: "9090-minioconso"
              containerPort: 9090
          volumeMounts:
            - name: storage-minio
              mountPath: "/data"
      volumes:
        - name: storage-minio
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: pvc-minio
          # hostPath:
          #   path: /storage/db/minio
