apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
