apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:1.94.0
          ports:
            - containerPort: 5678
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_TYPE
              value: "postgres"
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: s-pg-superuser
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s-pg-superuser
                  key: password
            - name: DB_POSTGRESDB_HOST
              value: "pg-n8n-rw.n8n.svc.cluster.local"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "admin"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "admin"
            - name: N8N_HOST
              value: n8n.local
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: "http://n8n.local/"
