---
apiVersion: v1
kind: Service
metadata:
  name: svce-n8n
  namespace: n8n
spec:
  type: NodePort
  ports:
  - name: n8n-tcp
    targetPort: 5678
    port: 80
    nodePort: 30013
    protocol: TCP
  selector:
    app: n8n