apiVersion: v1
kind: Service
metadata:
  name: svc-alertmanager-forwarder
  namespace: syrin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: alertmanager-forwarder
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: svce-alertmanager-forwarder
#   namespace: syrin
# spec:
#   type: NodePort
#   ports:
#   - name: alertmanager-forwarder-tcp
#     nodePort: 30010
#     port: 80
#     targetPort: 5000
#     protocol: TCP
#   selector:
#     app: alertmanager-forwarder