apiVersion: v1
kind: Service
metadata:
  name: svc-kokoro
  namespace: kokoro
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8880
  selector:
    app: kokoro
---
kind: Service
apiVersion: v1
metadata:
  name: svce-kokoro
  namespace: kokoro
spec:
  type: NodePort
  ports:
  - name: kokoro-tcp
    nodePort: 30017
    port: 80
    targetPort: 8880
    protocol: TCP
  selector:
    app: kokoro