apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-kokoro-cpu
  namespace: kokoro
  labels:
    app: kokoro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kokoro
  template:
    metadata:
      labels:
        app: kokoro
    spec:
      containers:
        - name: kokoro
          image: ghcr.io/remsky/kokoro-fastapi-cpu:latest #-> docker pull ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.1
          ports:
            - name: "8880-kokoro"
              containerPort: 8880
              protocol: TCP
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 8Gi
              cpu: 8.0
