##############################
# App Definition
app: syrin-install

##############################
# Definition of the Secret
secret:
  - name: rabbitmq
    type: Opaque
    data:
      RABBITMQ_DEFAULT_USER: cmFiYml0bXE= # rabbitmq
      RABBITMQ_DEFAULT_PASS: U3ZjUmFiYml0TXE= # SvcRabbitMq

  - name: minio
    type: Opaque
    data:
      MINIO_ROOT_USER: bWluaW8= #minio
      MINIO_ROOT_PASSWORD: TWluaW9TM1N1Y2Nlc3M= #MinioS3Success
      MINIO_ACCESS_KEY: N09vazNSaEVDSFpiblpKdEVaYTQ= #7Ook3RhECHZbnZJtEZa4
      MINIO_SECRET_KEY: cVJOaExSajZkME5UUjZiQ2JTSW5qZ2RwQW10dTdWTVU3ckpwckJHag== #qRNhLRj6d0NTR6bCbSInjgdpAmtu7VMU7rJprBGj

